# Generated by Django 5.0.6 on 2024-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='image',
            field=models.ImageField(upload_to='static/facility_images/'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='facility',
            field=models.CharField(choices=[('F1', '神立雪場'), ('F2', '石打丸山雪場'), ('F3', '苗場雪場'), ('F4', '舞子雪場')], default='', max_length=5),
        ),
    ]
