# Generated by Django 5.0.6 on 2024-06-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('FT', 'First Time'), ('GZ', 'Green Zone'), ('BZ', 'Blue Zone'), ('EXZ', 'Black Zone')], default='FT', max_length=5)),
            ],
        ),
    ]
