# Generated by Django 5.0.6 on 2024-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(choices=[('F1', 'FACILITY1'), ('F2', 'FACILITY2'), ('F3', 'FACILITY3'), ('F4', 'FACILITY4')], default='', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=15)),
            ],
        ),
    ]
