# Generated by Django 5.0.6 on 2024-07-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_tickets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress')], default='Open', max_length=20),
        ),
    ]
