# Generated by Django 5.0.6 on 2024-07-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_ticket_chat_thread_name_alter_chat_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='thread_name',
        ),
    ]
