# Generated by Django 5.0.6 on 2024-07-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_thread_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AddField(
            model_name='chat',
            name='sent_by',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
