# Generated by Django 5.0.6 on 2024-07-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_chat_message_room'),
        ('website', '0008_alter_tickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.tickets'),
            preserve_default=False,
        ),
    ]
