# Generated by Django 5.0.6 on 2024-08-02 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_room_ticket_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ticket_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
