# Generated by Django 5.0.6 on 2024-08-02 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_created_at'),
        ('website', '0008_alter_tickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ticket_seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='room_seller', to='website.tickets'),
            preserve_default=False,
        ),
    ]
